# Generated by Django 4.2.29 on 2026-03-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyrightForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_id', models.IntegerField()),
                ('author_id', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.IntegerField(default=0)),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('author_affiliation', models.CharField(blank=True, max_length=500, null=True)),
                ('co_authors_consent', models.BooleanField(default=False, null=True)),
                ('copyright_agreed', models.BooleanField(default=False, null=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('signed_date', models.DateTimeField(blank=True, null=True)),
                ('original_work', models.BooleanField(default=False, null=True)),
                ('no_conflict', models.BooleanField(default=False, null=True)),
                ('rights_transfer', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'copyright_form',
                'managed': True,
            },
        ),
    ]
