# Generated by Django 4.2.29 on 2026-04-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_reviewer_invitation_queued_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperAccessAuditLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("published_paper_id", models.IntegerField()),
                ("paper_submission_id", models.IntegerField(blank=True, null=True)),
                ("journal_id", models.IntegerField(blank=True, null=True)),
                ("old_access_type", models.CharField(max_length=20)),
                ("new_access_type", models.CharField(max_length=20)),
                ("changed_by_id", models.IntegerField(blank=True, null=True)),
                ("changed_by_email", models.CharField(blank=True, max_length=255, null=True)),
                ("changed_by_role", models.CharField(blank=True, max_length=50, null=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "paper_access_audit_log",
                "managed": True,
                "ordering": ["-changed_at"],
            },
        ),
    ]