# Generated by Django 4.2.29 on 2026-08-08 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_fix_paper_references_charset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('volume_no', models.IntegerField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('monograph', 'Monograph'), ('edited', 'Edited volume'), ('textbook', 'Textbook'), ('proceedings', 'Proceedings')], default='monograph', max_length=20)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=32, null=True)),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(default='English', max_length=32)),
                ('cover_image', models.CharField(blank=True, max_length=500, null=True)),
                ('is_open_access', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('published_on', models.DateField(blank=True, null=True)),
                ('conference_name', models.CharField(blank=True, max_length=500, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'book',
                'ordering': ['-published_on', '-id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DownloadAsset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('audience', models.CharField(choices=[('author', 'Authors'), ('editor', 'Editors'), ('forms', 'Forms'), ('reference', 'Reference')], default='author', max_length=20)),
                ('file', models.CharField(max_length=500)),
                ('file_format', models.CharField(blank=True, max_length=16, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('revised_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'download_asset',
                'ordering': ['audience', 'order', 'label'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProceedingsProposal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('conference_name', models.CharField(max_length=500)),
                ('organising_body', models.CharField(blank=True, max_length=500, null=True)),
                ('subject_area', models.CharField(blank=True, max_length=255, null=True)),
                ('conference_start', models.DateField(blank=True, null=True)),
                ('conference_end', models.DateField(blank=True, null=True)),
                ('expected_papers', models.IntegerField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=500, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='submitted', max_length=20)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(blank=True, db_column='submitted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'db_table': 'proceedings_proposal',
                'ordering': ['-submitted_on'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BookSeries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('series_editor', models.ForeignKey(blank=True, db_column='series_editor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_series', to='api.user')),
            ],
            options={
                'verbose_name_plural': 'book series',
                'db_table': 'book_series',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BookProposal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('kind', models.CharField(choices=[('monograph', 'Monograph'), ('edited', 'Edited volume'), ('textbook', 'Textbook'), ('proceedings', 'Proceedings')], default='monograph', max_length=20)),
                ('synopsis', models.TextField()),
                ('outline', models.TextField(blank=True, null=True)),
                ('audience', models.TextField(blank=True, null=True)),
                ('estimated_pages', models.IntegerField(blank=True, null=True)),
                ('outline_file', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=255)),
                ('affiliation', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='submitted', max_length=20)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(blank=True, db_column='series_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.bookseries')),
                ('submitted_by', models.ForeignKey(blank=True, db_column='submitted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'db_table': 'book_proposal',
                'ordering': ['-submitted_on'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BookContributor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('affiliation', models.CharField(blank=True, max_length=500, null=True)),
                ('role', models.CharField(choices=[('author', 'Author'), ('editor', 'Editor')], default='author', max_length=16)),
                ('order', models.IntegerField(default=0)),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='api.book')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'db_table': 'book_contributor',
                'ordering': ['book_id', 'order'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(blank=True, max_length=1000, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('start_page', models.IntegerField(blank=True, null=True)),
                ('end_page', models.IntegerField(blank=True, null=True)),
                ('pdf', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.IntegerField(default=0)),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='api.book')),
            ],
            options={
                'db_table': 'book_chapter',
                'ordering': ['book_id', 'order'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ForeignKey(blank=True, db_column='series_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='api.bookseries'),
        ),
    ]
