# Generated by Django 4.2.29 on 2026-08-08 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_book_downloadasset_proceedingsproposal_bookseries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookproposal',
            name='author_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookproposal',
            name='comparable_works',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookproposal',
            name='completion_status',
            field=models.CharField(blank=True, choices=[('idea', 'Idea stage'), ('partial', 'Partially drafted'), ('substantially', 'Substantially complete'), ('complete', 'Complete manuscript')], max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='bookproposal',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookproposal',
            name='cv_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bookproposal',
            name='decided_by',
            field=models.ForeignKey(blank=True, db_column='decided_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_book_proposals', to='api.user'),
        ),
        migrations.AddField(
            model_name='bookproposal',
            name='decided_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookproposal',
            name='decision_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookproposal',
            name='estimated_words',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookproposal',
            name='expected_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookproposal',
            name='illustration_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookproposal',
            name='previously_published',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookproposal',
            name='sample_chapter_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bookproposal',
            name='suggested_reviewers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proceedingsproposal',
            name='announcement_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='proceedingsproposal',
            name='conference_type',
            field=models.CharField(blank=True, choices=[('national', 'National'), ('international', 'International')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proceedingsproposal',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proceedingsproposal',
            name='contact_designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proceedingsproposal',
            name='decided_by',
            field=models.ForeignKey(blank=True, db_column='decided_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_proceedings_proposals', to='api.user'),
        ),
        migrations.AddField(
            model_name='proceedingsproposal',
            name='decided_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proceedingsproposal',
            name='decision_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proceedingsproposal',
            name='selection_process',
            field=models.CharField(blank=True, choices=[('peer_reviewed', 'Peer-reviewed'), ('non_reviewed', 'Not peer-reviewed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proceedingsproposal',
            name='venue',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
