# Generated by Django 4.2.29 on 2026-08-13 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_bookproposal_author_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='eisbn',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='managing_editor',
            field=models.ForeignKey(blank=True, db_column='managing_editor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_books', to='api.user'),
        ),
        migrations.AddField(
            model_name='book',
            name='production_status',
            field=models.CharField(choices=[('commissioned', 'Commissioned'), ('manuscript', 'Manuscript delivered'), ('copyediting', 'Copyediting'), ('typesetting', 'Typesetting'), ('proofs', 'Proofs with author'), ('published', 'Published')], default='commissioned', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='source_proposal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bookproposal',
            name='converted_book',
            field=models.ForeignKey(blank=True, db_column='converted_book_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.book'),
        ),
    ]
