# Generated by Django 4.2.29 on 2026-08-13 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_book_eisbn_book_managing_editor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='conference_acronym',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='conference_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='conference_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='conference_organiser',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='conference_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='conference_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='conference_venue',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='is_open_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proceedingsproposal',
            name='converted_book',
            field=models.ForeignKey(blank=True, db_column='converted_book_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.book'),
        ),
    ]
