# Generated by Django 4.2.29 on 2026-08-13 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_book_conference_acronym_book_conference_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookGuestEditor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('affiliation', models.CharField(blank=True, max_length=500, null=True)),
                ('invitation_token', models.CharField(max_length=255, unique=True)),
                ('token_expiry', models.DateTimeField()),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('declined', 'Declined'), ('removed', 'Removed')], default='invited', max_length=20)),
                ('invitation_message', models.TextField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('invited_on', models.DateTimeField(auto_now_add=True)),
                ('responded_on', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, related_name='guest_editors', to='api.book')),
                ('invited_by', models.ForeignKey(blank=True, db_column='invited_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.user')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_editorships', to='api.user')),
            ],
            options={
                'db_table': 'book_guest_editor',
                'ordering': ['book_id', 'order', 'id'],
                'managed': True,
                'unique_together': {('book', 'email')},
            },
        ),
    ]
