# Generated by Django 4.2.29 on 2026-09-05 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_bookguesteditor'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('internship', 'Internship'), ('contract', 'Contract')], default='full_time', max_length=20)),
                ('department', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField(blank=True, default='')),
                ('requirements', models.TextField(blank=True, default='')),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('experience_level', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_posting',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('resume_file', models.CharField(blank=True, max_length=500, null=True)),
                ('resume_text', models.TextField(blank=True, default='')),
                ('cover_letter', models.TextField(blank=True, default='')),
                ('portfolio_link', models.CharField(blank=True, default='', max_length=500)),
                ('github_link', models.CharField(blank=True, default='', max_length=500)),
                ('linkedin_link', models.CharField(blank=True, default='', max_length=500)),
                ('ai_score', models.IntegerField(default=0)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('screening_status', models.CharField(choices=[('new', 'New'), ('screening', 'Screening'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('interview', 'Interview'), ('hired', 'Hired')], default='new', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.jobposting')),
            ],
            options={
                'db_table': 'job_application',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InterviewInvitation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.CharField(blank=True, default='', max_length=200)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('meeting_link', models.CharField(blank=True, default='', max_length=500)),
                ('test_link', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, related_name='interview_invitations', to='api.jobapplication')),
            ],
            options={
                'db_table': 'interview_invitation',
                'ordering': ['-sent_at', '-created_at'],
                'managed': True,
            },
        ),
    ]
