# Generated by Django 4.2.29 on 2026-09-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_jobposting_jobapplication_interviewinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderCycleRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_started_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'reminder_cycle_run',
                'managed': True,
            },
        ),
    ]
