# Generated by Django 4.2.29 on 2026-09-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remindercyclerun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='ai_score',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='ai_summary',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='matched_skills',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='missing_skills',
        ),
    ]
