CREATE TABLE `user` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `email` varchar(255) NOT NULL UNIQUE, `password` varchar(255) NOT NULL, `role` varchar(50) NULL, `fname` varchar(100) NULL, `lname` varchar(100) NULL, `mname` varchar(100) NULL, `title` varchar(100) NULL, `affiliation` varchar(255) NULL, `specialization` longtext NULL, `contact` varchar(20) NULL, `address` longtext NULL, `added_on` datetime(6) NULL, `salutation` varchar(20) NULL, `designation` varchar(100) NULL, `department` varchar(200) NULL, `organisation` varchar(255) NULL);;
CREATE TABLE `journal` (`fld_id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `fld_journal_name` varchar(200) NULL, `freq` varchar(250) NULL, `issn_ol` varchar(250) NULL, `issn_prt` varchar(250) NULL, `cheif_editor` varchar(250) NULL, `co_editor` varchar(250) NULL, `password` varchar(100) NOT NULL, `abs_ind` varchar(300) NULL, `short_form` varchar(255) NOT NULL, `journal_image` varchar(255) NOT NULL, `journal_logo` varchar(200) NOT NULL, `guidelines` longtext NULL, `copyright` longtext NULL, `membership` longtext NULL, `subscription` longtext NULL, `publication` longtext NULL, `advertisement` longtext NULL, `description` longtext NULL, `added_on` date NOT NULL);;
CREATE TABLE `journal_details` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `journal_id` varchar(50) NOT NULL, `about_journal` longtext NULL, `cheif_say` longtext NULL, `aim_objective` longtext NULL, `criteria` longtext NULL, `scope` longtext NULL, `guidelines` longtext NULL, `readings` longtext NULL, `added_on` datetime(6) NOT NULL);;
CREATE TABLE `volume` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `journal` varchar(250) NOT NULL, `volume_no` integer NOT NULL, `year` varchar(200) NULL, `added_on` date NULL);;
CREATE TABLE `issue` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `pages` varchar(7) NULL, `month` varchar(16) NULL, `volume` integer NULL, `journal` integer NULL, `add_on` varchar(10) NULL, `issue_no` integer NULL, `complete_issue` varchar(10) NULL);;
CREATE TABLE `paper_published` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `title` varchar(250) NOT NULL, `abstract` varchar(2000) NOT NULL, `p_reference` longtext NULL, `author` varchar(1000) NOT NULL, `journal` varchar(250) NOT NULL, `journal_id` integer NOT NULL, `volume` varchar(250) NOT NULL, `issue` varchar(250) NOT NULL, `date` datetime(6) NOT NULL, `pages` varchar(250) NOT NULL, `keyword` varchar(300) NOT NULL, `language` varchar(20) NOT NULL, `paper` varchar(200) NULL, `access_type` varchar(20) NOT NULL, `email` varchar(100) NULL, `affiliation` varchar(500) NULL, `co_authors_json` longtext NULL, `doi` varchar(100) NULL, `doi_status` varchar(50) NOT NULL, `doi_registered_at` datetime(6) NULL, `crossref_batch_id` varchar(100) NULL, `paper_submission_id` integer NULL);;
CREATE TABLE `news` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `title` varchar(300) NOT NULL, `description` longtext NULL, `added_on` date NULL, `journal_id` integer NULL);;
CREATE TABLE `user_role` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` integer NOT NULL, `role` varchar(50) NOT NULL, `status` varchar(20) NOT NULL, `requested_at` datetime(6) NOT NULL, `approved_by` integer NULL, `approved_at` datetime(6) NULL, `rejected_reason` longtext NULL, `journal_id` integer NULL, `editor_type` varchar(50) NULL);;
CREATE TABLE `role_request` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` integer NOT NULL, `requested_role` varchar(50) NOT NULL, `status` varchar(20) NOT NULL, `reason` longtext NULL, `requested_at` datetime(6) NOT NULL, `processed_by` integer NULL, `processed_at` datetime(6) NULL, `admin_notes` longtext NULL);;
CREATE TABLE `paper` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `paper_code` varchar(200) NOT NULL, `journal` integer NULL, `title` varchar(500) NOT NULL, `abstract` varchar(2500) NOT NULL, `keyword` varchar(1000) NOT NULL, `file` varchar(200) NOT NULL, `title_page` varchar(200) NULL, `blinded_manuscript` varchar(200) NULL, `revised_track_changes` varchar(200) NULL, `revised_clean` varchar(200) NULL, `response_to_reviewer` varchar(200) NULL, `added_on` datetime(6) NULL, `added_by` varchar(100) NOT NULL, `status` varchar(50) NOT NULL, `mailstatus` varchar(10) NOT NULL, `volume` varchar(100) NOT NULL, `issue` varchar(100) NOT NULL, `author` varchar(100) NOT NULL, `coauth` varchar(200) NOT NULL, `rev` varchar(200) NOT NULL, `version_number` integer NOT NULL, `revision_count` integer NOT NULL, `revision_deadline` datetime(6) NULL, `revision_notes` longtext NULL, `revision_requested_date` datetime(6) NULL, `revision_type` varchar(20) NULL, `editor_comments` longtext NULL, `research_area` varchar(200) NULL, `message_to_editor` longtext NULL, `terms_accepted` bool NOT NULL);;
CREATE TABLE `paper_comment` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `paper_id` integer NULL, `comment_by` varchar(255) NULL, `comment_text` longtext NULL, `added_on` datetime(6) NULL);;
CREATE TABLE `online_review` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `paper_id` integer NULL, `reviewer_id` varchar(100) NULL, `assigned_on` date NULL, `submitted_on` datetime(6) NULL, `date_submitted` datetime(6) NULL, `review_status` varchar(50) NOT NULL, `review_submission_id` integer NULL, `invitation_id` integer NULL, `due_date` datetime(6) NULL);;
CREATE TABLE `editor` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `editor_name` varchar(100) NULL, `editor_email` varchar(100) NULL, `editor_address` varchar(200) NULL, `editor_contact` varchar(100) NULL, `editor_affiliation` varchar(200) NULL, `editor_department` varchar(200) NULL, `editor_college` varchar(200) NULL, `password` varchar(200) NULL, `journal_id` integer NULL, `role` varchar(50) NULL, `editor_type` varchar(50) NULL, `added_on` datetime(6) NULL);;
CREATE TABLE `reviewer_invitation` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `paper_id` integer NOT NULL, `reviewer_id` integer NULL, `reviewer_email` varchar(255) NOT NULL, `reviewer_name` varchar(255) NULL, `journal_id` varchar(100) NULL, `invitation_token` varchar(255) NOT NULL, `token_expiry` datetime(6) NOT NULL, `status` varchar(50) NOT NULL, `invited_on` datetime(6) NULL, `accepted_on` datetime(6) NULL, `declined_on` datetime(6) NULL, `invitation_message` longtext NULL, `decline_reason` longtext NULL, `is_external` bool NOT NULL);;
CREATE TABLE `review_submission` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `paper_id` integer NOT NULL, `reviewer_id` varchar(100) NOT NULL, `assignment_id` integer NULL, `paper_version` integer NOT NULL, `technical_quality` integer NULL, `clarity` integer NULL, `originality` integer NULL, `significance` integer NULL, `overall_rating` integer NULL, `author_comments` longtext NULL, `confidential_comments` longtext NULL, `recommendation` varchar(50) NULL, `review_report_file` varchar(500) NULL, `file_version` integer NOT NULL, `status` varchar(50) NOT NULL, `created_at` datetime(6) NULL, `updated_at` datetime(6) NULL, `submitted_at` datetime(6) NULL);;
CREATE TABLE `paper_co_author` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `paper_id` integer NOT NULL, `salutation` varchar(20) NULL, `first_name` varchar(100) NOT NULL, `middle_name` varchar(100) NULL, `last_name` varchar(100) NOT NULL, `email` varchar(255) NULL, `designation` varchar(100) NULL, `department` varchar(200) NULL, `organisation` varchar(255) NULL, `author_order` integer NOT NULL, `is_corresponding` bool NOT NULL, `created_at` datetime(6) NULL);;
CREATE TABLE `email_template` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(100) NOT NULL, `slug` varchar(50) NOT NULL UNIQUE, `subject` varchar(500) NOT NULL, `body_template` longtext NOT NULL, `placeholders` longtext NULL, `category` varchar(50) NOT NULL, `is_active` bool NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NULL);;
CREATE TABLE `paper_correspondence` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `paper_id` integer NOT NULL, `sender_id` integer NULL, `sender_role` varchar(50) NULL, `recipient_email` varchar(255) NOT NULL, `recipient_name` varchar(255) NULL, `subject` varchar(500) NOT NULL, `body` longtext NOT NULL, `template_id` integer NULL, `email_type` varchar(50) NOT NULL, `status_at_send` varchar(50) NULL, `is_read` bool NOT NULL, `read_at` datetime(6) NULL, `delivery_status` varchar(50) NOT NULL, `webhook_id` varchar(100) NULL, `webhook_received_at` datetime(6) NULL, `error_message` longtext NULL, `retry_count` integer NOT NULL, `created_at` datetime(6) NULL, `sent_at` datetime(6) NULL);;
CREATE TABLE `paper_version` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `paper_id` integer NOT NULL, `version_number` integer NOT NULL, `file` varchar(200) NOT NULL, `file_size` integer NULL, `uploaded_on` datetime(6) NULL, `revision_reason` longtext NULL, `change_summary` longtext NULL, `uploaded_by` varchar(100) NOT NULL);;
CREATE TABLE `copyright_form` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `paper_id` integer NOT NULL, `author_id` integer NOT NULL, `status` varchar(20) NOT NULL DEFAULT 'pending', `deadline` datetime(6) NULL, `reminder_count` integer NOT NULL DEFAULT 0, `last_reminder_at` datetime(6) NULL, `author_name` varchar(255) NULL, `author_affiliation` varchar(500) NULL, `co_authors_consent` bool NULL DEFAULT 0, `copyright_agreed` bool NULL DEFAULT 0, `signature` varchar(255) NULL, `signed_date` datetime(6) NULL, `original_work` bool NULL DEFAULT 0, `no_conflict` bool NULL DEFAULT 0, `rights_transfer` bool NULL DEFAULT 0, `created_at` datetime(6) NULL, `completed_at` datetime(6) NULL);;

-- Seed admin user (email: admin@breakthroughpublishers.com, password: Admin@123)
INSERT INTO `user` (`email`, `password`, `role`, `fname`, `lname`, `added_on`) 
VALUES ('admin@breakthroughpublishers.com', '$2b$12$kg1dvhFO714To0k.79IsyOnZUl.k2jA5k8BuV40teBhHAoZVR8UvS', 'admin', 'Admin', 'User', NOW());
